;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        forward-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
